---
defaults: &defaults
  app_name: "barcode-mobile"
  connection:
    kafka: "dev01dsk2.dsk2.picompany.ru:9092"
    # zookeeper: "kafka.dev:2181"
    # redis: "redis://kafka.dev:6379"
    timeout_in_ms: 500

development:
  <<: *defaults

production:
  <<: *defaults
